### ISSUE TITLE
Persist if register was triggered

### ISSUE THREAD

**Issue by ilanolkies** [rnsdomains/rns-manager-react#132] opened 2020-02-06 04:22 UTC
Steps to reproduce:
1. Search for an available domain
2. Register
3. Submit commitment
4. Wait and click on register
5. _Reload. Now the registration starts back from commitment._

**Comment by jessgusclark** [comment] 2020-02-24 10:35
@ilanolkies 

I can't reproduce this error. I believe this was fixed with some of the recent commits regarding localstorage or with the redesign of the registration process.

A user can quit at any step now and with the local storage, pick up where they left off. The only exception is if the user clears their localstorage.

**Comment by ilanolkies** [comment] 2020-02-24 16:09
Clarification: confirm register, reload screen before it is confirmed.

**Closed** 2020-02-27 14:01 UTC
Labels: bug
