### ISSUE TITLE
Go to top when changing pages

### ISSUE THREAD

**Issue by ilanolkies** [rnsdomains/rns-manager-react#303] opened 2020-06-04 00:54 UTC
Now if you change a page it remains on the bottom. I think this is not so friendly. You can try it with the resolve button in the footer, it seems nothing happened.

**Comment by jessgusclark** [comment] 2020-06-17 11:36
This is a duplicate of #173 and was resolved with pull request #315.

**Closed by jessgusclark** 2020-06-17 11:36 UTC
Labels: ux
